package edu.eci.dosw.techcup.enums;

public enum StudentProgram {
	SYSTEMS_ENGINEERING,
	AI_ENGINEERING,
	CYBERSECURITY_ENGINEERING,
	STATISTICS_ENGINEERING,
	MASTERS_INFO_MANAGEMENT,
	MASTERS_INFORMATICS,
	MASTERS_DATA_SCIENCE
}
